export const ASSET_CATEGORIES = {
  LAPTOP: 'LAPTOP',
  DESKTOP: 'DESKTOP',
  MONITOR: 'MONITOR',
  KEYBOARD: 'KEYBOARD',
  MOUSE: 'MOUSE',
  HEADPHONE: 'HEADPHONE',
  PHONE: 'PHONE',
  TABLET: 'TABLET',
  FURNITURE: 'FURNITURE',
  EQUIPMENT: 'EQUIPMENT',
  OTHER: 'OTHER',
} as const;

export const ASSET_STATUSES = {
  AVAILABLE: 'AVAILABLE',
  ASSIGNED: 'ASSIGNED',
  MAINTENANCE: 'MAINTENANCE',
  RETIRED: 'RETIRED',
  LOST: 'LOST',
  DAMAGED: 'DAMAGED',
} as const;

export const ASSET_REQUEST_TYPES = {
  REQUEST: 'REQUEST',
  RETURN: 'RETURN',
  MAINTENANCE: 'MAINTENANCE',
} as const;

export const ASSET_REQUEST_STATUSES = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  FULFILLED: 'FULFILLED',
  RETURNED: 'RETURNED',
  CANCELLED: 'CANCELLED',
} as const;

export const ASSET_PRIORITIES = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;

// Device categories for filtering
export const DEVICE_CATEGORIES = [
  ASSET_CATEGORIES.LAPTOP,
  ASSET_CATEGORIES.DESKTOP,
  ASSET_CATEGORIES.MONITOR,
  ASSET_CATEGORIES.KEYBOARD,
  ASSET_CATEGORIES.MOUSE,
  ASSET_CATEGORIES.HEADPHONE,
  ASSET_CATEGORIES.PHONE,
  ASSET_CATEGORIES.TABLET,
];

// Category labels for UI
export const ASSET_CATEGORY_LABELS = {
  [ASSET_CATEGORIES.LAPTOP]: 'Laptop',
  [ASSET_CATEGORIES.DESKTOP]: 'Desktop',
  [ASSET_CATEGORIES.MONITOR]: 'Monitor',
  [ASSET_CATEGORIES.KEYBOARD]: 'Keyboard',
  [ASSET_CATEGORIES.MOUSE]: 'Mouse',
  [ASSET_CATEGORIES.HEADPHONE]: 'Headphone',
  [ASSET_CATEGORIES.PHONE]: 'Phone',
  [ASSET_CATEGORIES.TABLET]: 'Tablet',
  [ASSET_CATEGORIES.FURNITURE]: 'Furniture',
  [ASSET_CATEGORIES.EQUIPMENT]: 'Equipment',
  [ASSET_CATEGORIES.OTHER]: 'Other',
} as const;

// Status labels for UI
export const ASSET_STATUS_LABELS = {
  [ASSET_STATUSES.AVAILABLE]: 'Có sẵn',
  [ASSET_STATUSES.ASSIGNED]: 'Đã gán',
  [ASSET_STATUSES.MAINTENANCE]: 'Bảo trì',
  [ASSET_STATUSES.RETIRED]: 'Ngừng sử dụng',
  [ASSET_STATUSES.LOST]: 'Mất',
  [ASSET_STATUSES.DAMAGED]: 'Hỏng',
} as const;

// Priority labels for UI
export const ASSET_PRIORITY_LABELS = {
  [ASSET_PRIORITIES.LOW]: 'Thấp',
  [ASSET_PRIORITIES.NORMAL]: 'Bình thường',
  [ASSET_PRIORITIES.HIGH]: 'Cao',
  [ASSET_PRIORITIES.URGENT]: 'Khẩn cấp',
} as const;
